services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: l4h-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SecureTest123!
      MSSQL_PID: Express
    ports:
      - "14333:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SecureTest123! -Q 'SELECT 1'"]
      interval: 10s
      retries: 5
      timeout: 5s

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: l4h-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=L4H;User Id=sa;Password=SecureTest123!;TrustServerCertificate=True;
      - Logging__LogLevel__Default=Information
      - ADMIN_SEED_PASSWORD=SecureTest123!
    ports:
      - "8765:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./data/uploads:/app/uploads
    restart: unless-stopped

  law4hire:
    build:
      context: ./web/l4h
      dockerfile: Dockerfile
    container_name: l4h-web
    ports:
      - "5173:80"
    depends_on:
      - api

  cannlaw:
    build:
      context: ./web/cannlaw
      dockerfile: Dockerfile
    container_name: cannlaw-web
    ports:
      - "5174:80"
    depends_on:
      - api

volumes:
  sqlserver_data:
    driver: local
