USE L4H;
GO

INSERT INTO VisaTypes (Code, Name, IsActive, CreatedAt, UpdatedAt)
SELECT Code, Name, 1, GETDATE(), GETDATE()
FROM (VALUES 
    ('A-1', 'Ambassadors, Public Ministers, Career Diplomats'),
    ('A-2', 'Other Foreign Government Officials'),
    ('A-3', 'Attendants/Servants of A-1/A-2'),
    ('B-1', 'Temporary Business Visitor'),
    ('B-2', 'Temporary Tourist Visitor'),
    ('C-1', 'Transit'),
    ('C-1/D', 'Combined Transit and Crewmember'),
    ('C-2', 'UN Transit'),
    ('C-3', 'Foreign Government Transit'),
    ('CW-1', 'CNMI-Only Transitional Worker'),
    ('CW-2', 'Spouse/Child of CW-1'),
    ('D', 'Crewmember'),
    ('E-1', 'Treaty Trader'),
    ('E-2', 'Treaty Investor'),
    ('E-2C', 'CNMI Investor'),
    ('E-3', 'Australian Specialty Occupation'),
    ('E-3D', 'Spouse/Child of E-3'),
    ('E-3R', 'Returning E-3'),
    ('EB-1', 'Priority Workers'),
    ('EB-2', 'Professionals with Advanced Degrees'),
    ('EB-3', 'Skilled Workers/Professionals'),
    ('EB-4', 'Special Immigrants'),
    ('EB-5', 'Immigrant Investors'),
    ('F-1', 'Academic Student'),
    ('F-2', 'Spouse/Child of F-1'),
    ('F-3', 'Border Commuter Student'),
    ('G-1', 'Resident Representative to Int. Org'),
    ('G-2', 'Other Representative to Int. Org'),
    ('G-3', 'Non-recognized Representative'),
    ('G-4', 'Officer/Employee of Int. Org'),
    ('G-5', 'Attendant/Servant of G-1 to G-4'),
    ('H-1B', 'Specialty Occupation Worker'),
    ('H-1B1', 'Specialty Occupation (Chile/Singapore)'),
    ('H-1C', 'Nurse (Relief Act)'),
    ('H-2A', 'Agricultural Worker'),
    ('H-2B', 'Non-agricultural Worker'),
    ('H-3', 'Trainee/Special Education'),
    ('H-4', 'Spouse/Child of H-1/H-2/H-3'),
    ('I', 'Foreign Media Representative'),
    ('J-1', 'Exchange Visitor'),
    ('J-2', 'Spouse/Child of J-1'),
    ('K-1', 'Fiancé(e)'),
    ('K-2', 'Child of K-1'),
    ('K-3', 'Spouse of USC awaiting visa'),
    ('K-4', 'Child of K-3'),
    ('L-1A', 'Intracompany Manager/Executive'),
    ('L-1B', 'Intracompany Specialized Knowledge'),
    ('L-2', 'Spouse/Child of L-1'),
    ('M-1', 'Vocational Student'),
    ('M-2', 'Spouse/Child of M-1'),
    ('M-3', 'Border Commuter Vocational'),
    ('N-8', 'Parent of SK-3 Special Immigrant'),
    ('N-9', 'Child of N-8 or SK-1/2/4'),
    ('NATO-1', 'Principal Perm. Rep. to NATO'),
    ('NATO-2', 'Other Rep. to NATO'),
    ('NATO-3', 'Official Clerical Staff of NATO'),
    ('NATO-4', 'Official of NATO (Other)'),
    ('NATO-5', 'Expert employed by NATO'),
    ('NATO-6', 'Member of Civilian Component'),
    ('NATO-7', 'Attendant/Servant of NATO-1 to 6'),
    ('O-1', 'Extraordinary Ability'),
    ('O-2', 'Support Personnel for O-1'),
    ('O-3', 'Spouse/Child of O-1/O-2'),
    ('P-1', 'Internationally Recognized Athlete/Group'),
    ('P-2', 'Reciprocal Exchange Artist'),
    ('P-3', 'Culturally Unique Artist'),
    ('P-4', 'Spouse/Child of P-1/2/3'),
    ('Q-1', 'Cultural Exchange Visitor'),
    ('R-1', 'Religious Worker'),
    ('R-2', 'Spouse/Child of R-1'),
    ('S-5', 'Informant (Criminal Org)'),
    ('S-6', 'Informant (Terrorism)'),
    ('S-7', 'Spouse/Child of S-5/6'),
    ('SIJ', 'Special Immigrant Juvenile'),
    ('T-1', 'Victim of Human Trafficking'),
    ('T-2', 'Spouse of T-1'),
    ('T-3', 'Child of T-1'),
    ('T-4', 'Parent of T-1'),
    ('T-5', 'Sibling of T-1'),
    ('T-6', 'Adult/Minor Child of T-1'),
    ('TN', 'NAFTA Professional'),
    ('TD', 'Spouse/Child of TN'),
    ('TPS', 'Temporary Protected Status'),
    ('U-1', 'Victim of Criminal Activity'),
    ('U-2', 'Spouse of U-1'),
    ('U-3', 'Child of U-1'),
    ('U-4', 'Parent of U-1'),
    ('U-5', 'Sibling of U-1'),
    ('V-1', 'Spouse of LPR (LIFE Act)'),
    ('V-2', 'Child of V-1'),
    ('V-3', 'Child of V-1/V-2'),
    ('Diversity', 'Diversity Visa (Lottery)'),
    ('IR-1', 'Spouse of US Citizen'),
    ('IR-2', 'Child of US Citizen'),
    ('IR-3', 'Orphan Adopted Abroad'),
    ('IR-4', 'Orphan to be Adopted in US'),
    ('IR-5', 'Parent of US Citizen'),
    ('F1-Im', 'Unmarried Son/Daughter of USC'),
    ('F2A', 'Spouse/Child of LPR'),
    ('F2B', 'Unmarried Son/Daughter of LPR'),
    ('F3-Im', 'Married Son/Daughter of USC'),
    ('F4', 'Sibling of USC'),
    ('NATZ', 'Naturalization'),
    ('ADOP', 'Adoption'),
    ('ASYL', 'Asylum'),
    ('NIW', 'National Interest Waiver'),
    ('VAWA', 'Violence Against Women Act'),
    ('PARL', 'Humanitarian Parole'),
    ('WAV', 'Waivers'),
    ('DEP', 'Deportation Defense')
) AS Source (Code, Name)
WHERE NOT EXISTS (SELECT 1 FROM VisaTypes WHERE Code = Source.Code);

SELECT COUNT(*) FROM VisaTypes;
