BEGIN TRANSACTION;

-- DS Forms
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'DS-156') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'DS-156', 'Nonimmigrant Visa Application', 'Nonimmigrant Visa Application', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'DS-230') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'DS-230', 'Application for Immigrant Visa and Alien Registration', 'Application for Immigrant Visa and Alien Registration', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'DS-260') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'DS-260', 'Immigrant Visa Electronic Application', 'Immigrant Visa Electronic Application', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'DS-261') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'DS-261', 'Choice of Address and Agent', 'Choice of Address and Agent', 1, GETUTCDATE(), GETUTCDATE());

-- AR Forms
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'AR-11') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'AR-11', 'Alien''s Change of Address Card', 'Alien''s Change of Address Card', 1, GETUTCDATE(), GETUTCDATE());

-- EOIR Forms
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'EOIR-29') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'EOIR-29', 'Notice of Appeal to the BIA from a Decision of a DHS Officer', 'Notice of Appeal to the BIA from a Decision of a DHS Officer', 1, GETUTCDATE(), GETUTCDATE());

-- G Forms
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-28I') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-28I', 'Notice of Entry of Appearance as Attorney Outside the US', 'Notice of Entry of Appearance as Attorney Outside the US', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-325A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-325A', 'Biographic Information (for Deferred Action)', 'Biographic Information (for Deferred Action)', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-325R') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-325R', 'Biographic Information (Registration)', 'Biographic Information (Registration)', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-639') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-639', 'Freedom of Information/Privacy Act Request', 'Freedom of Information/Privacy Act Request', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-845') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-845', 'Verification Request', 'Verification Request', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-884') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-884', 'Request for the Return of Original Documents', 'Request for the Return of Original Documents', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-1041') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-1041', 'Genealogy Index Search Request', 'Genealogy Index Search Request', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-1041A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-1041A', 'Genealogy Records Request', 'Genealogy Records Request', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-1145') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-1145', 'E-Notification of Application/Petition Acceptance', 'E-Notification of Application/Petition Acceptance', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-1256') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-1256', 'Declaration for Interpreted USCIS Interview', 'Declaration for Interpreted USCIS Interview', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-1450') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-1450', 'Authorization for Credit Card Transactions', 'Authorization for Credit Card Transactions', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'G-1566') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'G-1566', 'Request for Certificate of Non-Existence', 'Request for Certificate of Non-Existence', 1, GETUTCDATE(), GETUTCDATE());

-- I Forms
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-9') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-9', 'Employment Eligibility Verification', 'Employment Eligibility Verification', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-102') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-102', 'Application for Replacement/Initial Nonimmigrant Arrival-Departure Document', 'Application for Replacement/Initial Nonimmigrant Arrival-Departure Document', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-129CW') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-129CW', 'Petition for a CNMI-Only Nonimmigrant Transitional Worker', 'Petition for a CNMI-Only Nonimmigrant Transitional Worker', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-129CWR') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-129CWR', 'Semiannual Report for CW-1 Employers', 'Semiannual Report for CW-1 Employers', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-129F') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-129F', 'Petition for Alien Fiancé(e)', 'Petition for Alien Fiancé(e)', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-131') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-131', 'Application for Travel Document', 'Used to request Advance Parole or a Re-entry Permit.', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-131A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-131A', 'Application for Carrier Documentation', 'Application for Carrier Documentation', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-134') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-134', 'Declaration of Financial Support', 'Declaration of Financial Support', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-140G') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-140G', 'Immigrant Petition for the Gold Card Program', 'Immigrant Petition for the Gold Card Program', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-191') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-191', 'Application for Relief Under Former Section 212(c) of the INA', 'Application for Relief Under Former Section 212(c) of the INA', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-192') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-192', 'Application for Advance Permission to Enter as a Nonimmigrant', 'Application for Advance Permission to Enter as a Nonimmigrant', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-193') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-193', 'Application for Waiver of Passport and/or Visa', 'Application for Waiver of Passport and/or Visa', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-212') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-212', 'Application for Permission to Reapply for Admission After Deportation', 'Application for Permission to Reapply for Admission After Deportation', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-290B') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-290B', 'Notice of Appeal or Motion', 'Notice of Appeal or Motion', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-356') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-356', 'Request for Cancellation of Public Charge Bond', 'Request for Cancellation of Public Charge Bond', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-360') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-360', 'Petition for Amerasian, Widow(er), or Special Immigrant', 'Petition for Amerasian, Widow(er), or Special Immigrant', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-361') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-361', 'Affidavit of Financial Support for Public Law 97-359 Amerasian', 'Affidavit of Financial Support for Public Law 97-359 Amerasian', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-407') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-407', 'Record of Abandonment of Lawful Permanent Resident Status', 'Record of Abandonment of Lawful Permanent Resident Status', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-485A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-485A', 'Supplement A to Form I-485, Adjustment of Status Under Section 245(i)', 'Supplement A to Form I-485, Adjustment of Status Under Section 245(i)', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-485J') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-485J', 'Confirmation of Valid Job Offer or Request for Job Portability', 'Confirmation of Valid Job Offer or Request for Job Portability', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-508') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-508', 'Request for Waiver of Certain Rights, Privileges, Exemptions and Immunities', 'Request for Waiver of Certain Rights, Privileges, Exemptions and Immunities', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-526') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-526', 'Immigrant Petition by Standalone Investor', 'Immigrant Petition by Standalone Investor', 1, GETUTCDATE(), GETUTCDATE());        
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-526E') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-526E', 'Immigrant Petition by Regional Center Investor', 'Immigrant Petition by Regional Center Investor', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-539') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-539', 'Application To Extend/Change Nonimmigrant Status', 'Used to extend stay or change to another nonimmigrant status while in the United States.', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-566') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-566', 'Interagency Record of Request for A, G, or NATO Dependent Employment Authorization', 'Interagency Record of Request for A, G, or NATO Dependent Employment Authorization', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-589') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-589', 'Application for Asylum and for Withholding of Removal', 'Application for Asylum and for Withholding of Removal', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-600') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-600', 'Petition to Classify Orphan as an Immediate Relative', 'Petition to Classify Orphan as an Immediate Relative', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-600A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-600A', 'Application for Advance Processing of Orphan Petition', 'Application for Advance Processing of Orphan Petition', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-601') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-601', 'Application for Waiver of Grounds of Inadmissibility', 'Application for Waiver of Grounds of Inadmissibility', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-601A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-601A', 'Application for Provisional Unlawful Presence Waiver', 'Application for Provisional Unlawful Presence Waiver', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-612') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-612', 'Application for Waiver of the Foreign Residence Requirement', 'Application for Waiver of the Foreign Residence Requirement', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-687') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-687', 'Application for Status as a Temporary Resident Under Section 245A of the INA', 'Application for Status as a Temporary Resident Under Section 245A of the INA', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-690') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-690', 'Application for Waiver of Grounds of Inadmissibility Under Sections 245A or 210', 'Application for Waiver of Grounds of Inadmissibility Under Sections 245A or 210', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-694') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-694', 'Notice of Appeal of Decision Under Sections 210 or 245A', 'Notice of Appeal of Decision Under Sections 210 or 245A', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-698') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-698', 'Application to Adjust Status from Temporary to Permanent Resident', 'Application to Adjust Status from Temporary to Permanent Resident', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-730') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-730', 'Refugee/Asylee Relative Petition', 'Refugee/Asylee Relative Petition', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-751') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-751', 'Petition to Remove Conditions on Residence', 'Petition to Remove Conditions on Residence', 1, GETUTCDATE(), GETUTCDATE());      
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-765') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-765', 'Application for Employment Authorization', 'Used to request work authorization (EAD).', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-765V') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-765V', 'Employment Authorization for Abused Nonimmigrant Spouse', 'Employment Authorization for Abused Nonimmigrant Spouse', 1, GETUTCDATE(), GETUTCDATE());IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-800') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-800', 'Petition to Classify Convention Adoptee as an Immediate Relative', 'Petition to Classify Convention Adoptee as an Immediate Relative', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-800A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-800A', 'Suitability to Adopt a Child from a Convention Country', 'Suitability to Adopt a Child from a Convention Country', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-817') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-817', 'Application for Family Unity Benefits', 'Application for Family Unity Benefits', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-821') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-821', 'Application for Temporary Protected Status', 'Application for Temporary Protected Status', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-821D') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-821D', 'Consideration of Deferred Action for Childhood Arrivals', 'Consideration of Deferred Action for Childhood Arrivals', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-824') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-824', 'Application for Action on an Approved Application or Petition', 'Application for Action on an Approved Application or Petition', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-829') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-829', 'Petition by Investor to Remove Conditions on Permanent Resident Status', 'Petition by Investor to Remove Conditions on Permanent Resident Status', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-854') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-854', 'Inter-Agency Alien Witness and Informant Record', 'Inter-Agency Alien Witness and Informant Record', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-864A') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-864A', 'Contract Between Sponsor and Household Member', 'Contract Between Sponsor and Household Member', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-864EZ') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-864EZ', 'Affidavit of Support Under Section 213A of the INA', 'Affidavit of Support Under Section 213A of the INA', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-864W') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-864W', 'Exemption for Intending Immigrant''s Affidavit of Support', 'Exemption for Intending Immigrant''s Affidavit of Support', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-865') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-865', 'Sponsor''s Notice of Change of Address', 'Sponsor''s Notice of Change of Address', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-881') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-881', 'Application for Suspension of Deportation or Special Rule Cancellation', 'Application for Suspension of Deportation or Special Rule Cancellation', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-905') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-905', 'Authorization to Issue Certification for Health Care Workers', 'Authorization to Issue Certification for Health Care Workers', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-910') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-910', 'Application for Civil Surgeon Designation', 'Application for Civil Surgeon Designation', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-912') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-912', 'Request for Fee Waiver', 'Request for Fee Waiver', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-914') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-914', 'Application for T Nonimmigrant Status', 'Application for T Nonimmigrant Status', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-918') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-918', 'Petition for U Nonimmigrant Status', 'Petition for U Nonimmigrant Status', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-924') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-924', 'Application for Regional Center Designation', 'Application for Regional Center Designation', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-929') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-929', 'Petition for Qualifying Family Member of a U-1 Nonimmigrant', 'Petition for Qualifying Family Member of a U-1 Nonimmigrant', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-941') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-941', 'Application for Entrepreneur Parole', 'Application for Entrepreneur Parole', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-945') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-945', 'Public Charge Bond', 'Public Charge Bond', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-956') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-956', 'Application for Regional Center Designation', 'Application for Regional Center Designation', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-956F') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-956F', 'Approval of an Investment in a Commercial Enterprise', 'Approval of an Investment in a Commercial Enterprise', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-956G') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-956G', 'Regional Center Annual Statement', 'Regional Center Annual Statement', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-956H') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-956H', 'Bona Fides of Persons Involved with Regional Center Program', 'Bona Fides of Persons Involved with Regional Center Program', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'I-956K') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'I-956K', 'Registration for Direct and Third-Party Promoters', 'Registration for Direct and Third-Party Promoters', 1, GETUTCDATE(), GETUTCDATE());

-- N Forms
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-300') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-300', 'Application to File Declaration of Intention', 'Application to File Declaration of Intention', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-336') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-336', 'Request for a Hearing on a Decision in Naturalization Proceedings', 'Request for a Hearing on a Decision in Naturalization Proceedings', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-426') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-426', 'Request for Certification of Military or Naval Service', 'Request for Certification of Military or Naval Service', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-470') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-470', 'Application to Preserve Residence for Naturalization Purposes', 'Application to Preserve Residence for Naturalization Purposes', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-565') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-565', 'Application for Replacement Naturalization/Citizenship Document', 'Application for Replacement Naturalization/Citizenship Document', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-600') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-600', 'Application for Certificate of Citizenship', 'Application for Certificate of Citizenship', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-600K') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-600K', 'Citizenship and Issuance of Certificate Under Section 322', 'Citizenship and Issuance of Certificate Under Section 322', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-644') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-644', 'Application for Posthumous Citizenship', 'Application for Posthumous Citizenship', 1, GETUTCDATE(), GETUTCDATE());
IF NOT EXISTS (SELECT 1 FROM USCISForms WHERE FormNumber = 'N-648') INSERT INTO USCISForms (Id, FormNumber, FormName, Description, IsActive, CreatedAt, UpdatedAt) VALUES (NEWID(), 'N-648', 'Medical Certification for Disability Exceptions', 'Medical Certification for Disability Exceptions', 1, GETUTCDATE(), GETUTCDATE());

COMMIT;
