-- Insert ALL 197 countries and territories as requested
-- This script contains every single country, not just "major" ones

BEGIN TRANSACTION;

-- Africa (54 countries)
INSERT INTO Countries (Id, Name, CountryCode2, CountryCode, IsActive, SortOrder, CreatedAt, IsUNRecognized) VALUES
(NEWID(), 'Algeria', 'DZ', 'DZA', 1, 1, GETDATE(), 1),
(NEWID(), 'Angola', 'AO', 'AGO', 1, 2, GETDATE(), 1),
(NEWID(), 'Benin', 'BJ', 'BEN', 1, 3, GETDATE(), 1),
(NEWID(), 'Botswana', 'BW', 'BWA', 1, 4, GETDATE(), 1),
(NEWID(), 'Burkina Faso', 'BF', 'BFA', 1, 5, GETDATE(), 1),
(NEWID(), 'Burundi', 'BI', 'BDI', 1, 6, GETDATE(), 1),
(NEWID(), 'Cameroon', 'CM', 'CMR', 1, 7, GETDATE(), 1),
(NEWID(), 'Cape Verde', 'CV', 'CPV', 1, 8, GETDATE(), 1),
(NEWID(), 'Central African Republic', 'CF', 'CAF', 1, 9, GETDATE(), 1),
(NEWID(), 'Chad', 'TD', 'TCD', 1, 10, GETDATE(), 1),
(NEWID(), 'Comoros', 'KM', 'COM', 1, 11, GETDATE(), 1),
(NEWID(), 'Congo', 'CG', 'COG', 1, 12, GETDATE(), 1),
(NEWID(), 'Democratic Republic of the Congo', 'CD', 'COD', 1, 13, GETDATE(), 1),
(NEWID(), 'Côte d''Ivoire', 'CI', 'CIV', 1, 14, GETDATE(), 1),
(NEWID(), 'Djibouti', 'DJ', 'DJI', 1, 15, GETDATE(), 1),
(NEWID(), 'Egypt', 'EG', 'EGY', 1, 16, GETDATE(), 1),
(NEWID(), 'Equatorial Guinea', 'GQ', 'GNQ', 1, 17, GETDATE(), 1),
(NEWID(), 'Eritrea', 'ER', 'ERI', 1, 18, GETDATE(), 1),
(NEWID(), 'Ethiopia', 'ET', 'ETH', 1, 19, GETDATE(), 1),
(NEWID(), 'Gabon', 'GA', 'GAB', 1, 20, GETDATE(), 1),
(NEWID(), 'Gambia', 'GM', 'GMB', 1, 21, GETDATE(), 1),
(NEWID(), 'Ghana', 'GH', 'GHA', 1, 22, GETDATE(), 1),
(NEWID(), 'Guinea', 'GN', 'GIN', 1, 23, GETDATE(), 1),
(NEWID(), 'Guinea-Bissau', 'GW', 'GNB', 1, 24, GETDATE(), 1),
(NEWID(), 'Kenya', 'KE', 'KEN', 1, 25, GETDATE(), 1),
(NEWID(), 'Lesotho', 'LS', 'LSO', 1, 26, GETDATE(), 1),
(NEWID(), 'Liberia', 'LR', 'LBR', 1, 27, GETDATE(), 1),
(NEWID(), 'Libya', 'LY', 'LBY', 1, 28, GETDATE(), 1),
(NEWID(), 'Madagascar', 'MG', 'MDG', 1, 29, GETDATE(), 1),
(NEWID(), 'Malawi', 'MW', 'MWI', 1, 30, GETDATE(), 1),
(NEWID(), 'Mali', 'ML', 'MLI', 1, 31, GETDATE(), 1),
(NEWID(), 'Mauritania', 'MR', 'MRT', 1, 32, GETDATE(), 1),
(NEWID(), 'Mauritius', 'MU', 'MUS', 1, 33, GETDATE(), 1),
(NEWID(), 'Morocco', 'MA', 'MAR', 1, 34, GETDATE(), 1),
(NEWID(), 'Mozambique', 'MZ', 'MOZ', 1, 35, GETDATE(), 1),
(NEWID(), 'Namibia', 'NA', 'NAM', 1, 36, GETDATE(), 1),
(NEWID(), 'Niger', 'NE', 'NER', 1, 37, GETDATE(), 1),
(NEWID(), 'Nigeria', 'NG', 'NGA', 1, 38, GETDATE(), 1),
(NEWID(), 'Rwanda', 'RW', 'RWA', 1, 39, GETDATE(), 1),
(NEWID(), 'São Tomé and Príncipe', 'ST', 'STP', 1, 40, GETDATE(), 1),
(NEWID(), 'Senegal', 'SN', 'SEN', 1, 41, GETDATE(), 1),
(NEWID(), 'Seychelles', 'SC', 'SYC', 1, 42, GETDATE(), 1),
(NEWID(), 'Sierra Leone', 'SL', 'SLE', 1, 43, GETDATE(), 1),
(NEWID(), 'Somalia', 'SO', 'SOM', 1, 44, GETDATE(), 1),
(NEWID(), 'South Africa', 'ZA', 'ZAF', 1, 45, GETDATE(), 1),
(NEWID(), 'South Sudan', 'SS', 'SSD', 1, 46, GETDATE(), 1),
(NEWID(), 'Sudan', 'SD', 'SDN', 1, 47, GETDATE(), 1),
(NEWID(), 'Eswatini', 'SZ', 'SWZ', 1, 48, GETDATE(), 1),
(NEWID(), 'Tanzania', 'TZ', 'TZA', 1, 49, GETDATE(), 1),
(NEWID(), 'Togo', 'TG', 'TGO', 1, 50, GETDATE(), 1),
(NEWID(), 'Tunisia', 'TN', 'TUN', 1, 51, GETDATE(), 1),
(NEWID(), 'Uganda', 'UG', 'UGA', 1, 52, GETDATE(), 1),
(NEWID(), 'Zambia', 'ZM', 'ZMB', 1, 53, GETDATE(), 1),
(NEWID(), 'Zimbabwe', 'ZW', 'ZWE', 1, 54, GETDATE(), 1);

-- Asia (49 countries)  
INSERT INTO Countries (Id, Name, CountryCode2, CountryCode, IsActive, SortOrder, CreatedAt, IsUNRecognized) VALUES
(NEWID(), 'Afghanistan', 'AF', 'AFG', 1, 55, GETDATE(), 1),
(NEWID(), 'Armenia', 'AM', 'ARM', 1, 56, GETDATE(), 1),
(NEWID(), 'Azerbaijan', 'AZ', 'AZE', 1, 57, GETDATE(), 1),
(NEWID(), 'Bahrain', 'BH', 'BHR', 1, 58, GETDATE(), 1),
(NEWID(), 'Bangladesh', 'BD', 'BGD', 1, 59, GETDATE(), 1),
(NEWID(), 'Bhutan', 'BT', 'BTN', 1, 60, GETDATE(), 1),
(NEWID(), 'Brunei', 'BN', 'BRN', 1, 61, GETDATE(), 1),
(NEWID(), 'Cambodia', 'KH', 'KHM', 1, 62, GETDATE(), 1),
(NEWID(), 'China', 'CN', 'CHN', 1, 63, GETDATE(), 1),
(NEWID(), 'Cyprus', 'CY', 'CYP', 1, 64, GETDATE(), 1),
(NEWID(), 'Georgia', 'GE', 'GEO', 1, 65, GETDATE(), 1),
(NEWID(), 'India', 'IN', 'IND', 1, 66, GETDATE(), 1),
(NEWID(), 'Indonesia', 'ID', 'IDN', 1, 67, GETDATE(), 1),
(NEWID(), 'Iran', 'IR', 'IRN', 1, 68, GETDATE(), 1),
(NEWID(), 'Iraq', 'IQ', 'IRQ', 1, 69, GETDATE(), 1),
(NEWID(), 'Israel', 'IL', 'ISR', 1, 70, GETDATE(), 1),
(NEWID(), 'Japan', 'JP', 'JPN', 1, 71, GETDATE(), 1),
(NEWID(), 'Jordan', 'JO', 'JOR', 1, 72, GETDATE(), 1),
(NEWID(), 'Kazakhstan', 'KZ', 'KAZ', 1, 73, GETDATE(), 1),
(NEWID(), 'Kuwait', 'KW', 'KWT', 1, 74, GETDATE(), 1),
(NEWID(), 'Kyrgyzstan', 'KG', 'KGZ', 1, 75, GETDATE(), 1),
(NEWID(), 'Laos', 'LA', 'LAO', 1, 76, GETDATE(), 1),
(NEWID(), 'Lebanon', 'LB', 'LBN', 1, 77, GETDATE(), 1),
(NEWID(), 'Malaysia', 'MY', 'MYS', 1, 78, GETDATE(), 1),
(NEWID(), 'Maldives', 'MV', 'MDV', 1, 79, GETDATE(), 1),
(NEWID(), 'Mongolia', 'MN', 'MNG', 1, 80, GETDATE(), 1),
(NEWID(), 'Myanmar', 'MM', 'MMR', 1, 81, GETDATE(), 1),
(NEWID(), 'Nepal', 'NP', 'NPL', 1, 82, GETDATE(), 1),
(NEWID(), 'North Korea', 'KP', 'PRK', 1, 83, GETDATE(), 1),
(NEWID(), 'Oman', 'OM', 'OMN', 1, 84, GETDATE(), 1),
(NEWID(), 'Pakistan', 'PK', 'PAK', 1, 85, GETDATE(), 1),
(NEWID(), 'Palestine', 'PS', 'PSE', 1, 86, GETDATE(), 1),
(NEWID(), 'Philippines', 'PH', 'PHL', 1, 87, GETDATE(), 1),
(NEWID(), 'Qatar', 'QA', 'QAT', 1, 88, GETDATE(), 1),
(NEWID(), 'Saudi Arabia', 'SA', 'SAU', 1, 89, GETDATE(), 1),
(NEWID(), 'Singapore', 'SG', 'SGP', 1, 90, GETDATE(), 1),
(NEWID(), 'South Korea', 'KR', 'KOR', 1, 91, GETDATE(), 1),
(NEWID(), 'Sri Lanka', 'LK', 'LKA', 1, 92, GETDATE(), 1),
(NEWID(), 'Syria', 'SY', 'SYR', 1, 93, GETDATE(), 1),
(NEWID(), 'Taiwan', 'TW', 'TWN', 1, 94, GETDATE(), 1),
(NEWID(), 'Tajikistan', 'TJ', 'TJK', 1, 95, GETDATE(), 1),
(NEWID(), 'Thailand', 'TH', 'THA', 1, 96, GETDATE(), 1),
(NEWID(), 'Timor-Leste', 'TL', 'TLS', 1, 97, GETDATE(), 1),
(NEWID(), 'Turkey', 'TR', 'TUR', 1, 98, GETDATE(), 1),
(NEWID(), 'Turkmenistan', 'TM', 'TKM', 1, 99, GETDATE(), 1),
(NEWID(), 'United Arab Emirates', 'AE', 'ARE', 1, 100, GETDATE(), 1),
(NEWID(), 'Uzbekistan', 'UZ', 'UZB', 1, 101, GETDATE(), 1),
(NEWID(), 'Vietnam', 'VN', 'VNM', 1, 102, GETDATE(), 1),
(NEWID(), 'Yemen', 'YE', 'YEM', 1, 103, GETDATE(), 1);

-- Europe (45 countries)
INSERT INTO Countries (Id, Name, CountryCode2, CountryCode, IsActive, SortOrder, CreatedAt, IsUNRecognized) VALUES
(NEWID(), 'Albania', 'AL', 'ALB', 1, 104, GETDATE(), 1),
(NEWID(), 'Andorra', 'AD', 'AND', 1, 105, GETDATE(), 1),
(NEWID(), 'Austria', 'AT', 'AUT', 1, 106, GETDATE(), 1),
(NEWID(), 'Belarus', 'BY', 'BLR', 1, 107, GETDATE(), 1),
(NEWID(), 'Belgium', 'BE', 'BEL', 1, 108, GETDATE(), 1),
(NEWID(), 'Bosnia and Herzegovina', 'BA', 'BIH', 1, 109, GETDATE(), 1),
(NEWID(), 'Bulgaria', 'BG', 'BGR', 1, 110, GETDATE(), 1),
(NEWID(), 'Croatia', 'HR', 'HRV', 1, 111, GETDATE(), 1),
(NEWID(), 'Czech Republic', 'CZ', 'CZE', 1, 112, GETDATE(), 1),
(NEWID(), 'Denmark', 'DK', 'DNK', 1, 113, GETDATE(), 1),
(NEWID(), 'Estonia', 'EE', 'EST', 1, 114, GETDATE(), 1),
(NEWID(), 'Finland', 'FI', 'FIN', 1, 115, GETDATE(), 1),
(NEWID(), 'France', 'FR', 'FRA', 1, 116, GETDATE(), 1),
(NEWID(), 'Germany', 'DE', 'DEU', 1, 117, GETDATE(), 1),
(NEWID(), 'Greece', 'GR', 'GRC', 1, 118, GETDATE(), 1),
(NEWID(), 'Hungary', 'HU', 'HUN', 1, 119, GETDATE(), 1),
(NEWID(), 'Iceland', 'IS', 'ISL', 1, 120, GETDATE(), 1),
(NEWID(), 'Ireland', 'IE', 'IRL', 1, 121, GETDATE(), 1),
(NEWID(), 'Italy', 'IT', 'ITA', 1, 122, GETDATE(), 1),
(NEWID(), 'Kosovo', 'XK', 'XKX', 1, 123, GETDATE(), 1),
(NEWID(), 'Latvia', 'LV', 'LVA', 1, 124, GETDATE(), 1),
(NEWID(), 'Liechtenstein', 'LI', 'LIE', 1, 125, GETDATE(), 1),
(NEWID(), 'Lithuania', 'LT', 'LTU', 1, 126, GETDATE(), 1),
(NEWID(), 'Luxembourg', 'LU', 'LUX', 1, 127, GETDATE(), 1),
(NEWID(), 'Malta', 'MT', 'MLT', 1, 128, GETDATE(), 1),
(NEWID(), 'Moldova', 'MD', 'MDA', 1, 129, GETDATE(), 1),
(NEWID(), 'Monaco', 'MC', 'MCO', 1, 130, GETDATE(), 1),
(NEWID(), 'Montenegro', 'ME', 'MNE', 1, 131, GETDATE(), 1),
(NEWID(), 'Netherlands', 'NL', 'NLD', 1, 132, GETDATE(), 1),
(NEWID(), 'North Macedonia', 'MK', 'MKD', 1, 133, GETDATE(), 1),
(NEWID(), 'Norway', 'NO', 'NOR', 1, 134, GETDATE(), 1),
(NEWID(), 'Poland', 'PL', 'POL', 1, 135, GETDATE(), 1),
(NEWID(), 'Portugal', 'PT', 'PRT', 1, 136, GETDATE(), 1),
(NEWID(), 'Romania', 'RO', 'ROU', 1, 137, GETDATE(), 1),
(NEWID(), 'Russia', 'RU', 'RUS', 1, 138, GETDATE(), 1),
(NEWID(), 'San Marino', 'SM', 'SMR', 1, 139, GETDATE(), 1),
(NEWID(), 'Serbia', 'RS', 'SRB', 1, 140, GETDATE(), 1),
(NEWID(), 'Slovakia', 'SK', 'SVK', 1, 141, GETDATE(), 1),
(NEWID(), 'Slovenia', 'SI', 'SVN', 1, 142, GETDATE(), 1),
(NEWID(), 'Spain', 'ES', 'ESP', 1, 143, GETDATE(), 1),
(NEWID(), 'Sweden', 'SE', 'SWE', 1, 144, GETDATE(), 1),
(NEWID(), 'Switzerland', 'CH', 'CHE', 1, 145, GETDATE(), 1),
(NEWID(), 'Ukraine', 'UA', 'UKR', 1, 146, GETDATE(), 1),
(NEWID(), 'United Kingdom', 'GB', 'GBR', 1, 147, GETDATE(), 1),
(NEWID(), 'Vatican City', 'VA', 'VAT', 1, 148, GETDATE(), 1);

-- North America (23 countries)
INSERT INTO Countries (Id, Name, CountryCode2, CountryCode, IsActive, SortOrder, CreatedAt, IsUNRecognized) VALUES
(NEWID(), 'Antigua and Barbuda', 'AG', 'ATG', 1, 149, GETDATE(), 1),
(NEWID(), 'Bahamas', 'BS', 'BHS', 1, 150, GETDATE(), 1),
(NEWID(), 'Barbados', 'BB', 'BRB', 1, 151, GETDATE(), 1),
(NEWID(), 'Belize', 'BZ', 'BLZ', 1, 152, GETDATE(), 1),
(NEWID(), 'Canada', 'CA', 'CAN', 1, 153, GETDATE(), 1),
(NEWID(), 'Costa Rica', 'CR', 'CRI', 1, 154, GETDATE(), 1),
(NEWID(), 'Cuba', 'CU', 'CUB', 1, 155, GETDATE(), 1),
(NEWID(), 'Dominica', 'DM', 'DMA', 1, 156, GETDATE(), 1),
(NEWID(), 'Dominican Republic', 'DO', 'DOM', 1, 157, GETDATE(), 1),
(NEWID(), 'El Salvador', 'SV', 'SLV', 1, 158, GETDATE(), 1),
(NEWID(), 'Grenada', 'GD', 'GRD', 1, 159, GETDATE(), 1),
(NEWID(), 'Guatemala', 'GT', 'GTM', 1, 160, GETDATE(), 1),
(NEWID(), 'Haiti', 'HT', 'HTI', 1, 161, GETDATE(), 1),
(NEWID(), 'Honduras', 'HN', 'HND', 1, 162, GETDATE(), 1),
(NEWID(), 'Jamaica', 'JM', 'JAM', 1, 163, GETDATE(), 1),
(NEWID(), 'Mexico', 'MX', 'MEX', 1, 164, GETDATE(), 1),
(NEWID(), 'Nicaragua', 'NI', 'NIC', 1, 165, GETDATE(), 1),
(NEWID(), 'Panama', 'PA', 'PAN', 1, 166, GETDATE(), 1),
(NEWID(), 'Saint Kitts and Nevis', 'KN', 'KNA', 1, 167, GETDATE(), 1),
(NEWID(), 'Saint Lucia', 'LC', 'LCA', 1, 168, GETDATE(), 1),
(NEWID(), 'Saint Vincent and the Grenadines', 'VC', 'VCT', 1, 169, GETDATE(), 1),
(NEWID(), 'Trinidad and Tobago', 'TT', 'TTO', 1, 170, GETDATE(), 1),
(NEWID(), 'United States', 'US', 'USA', 1, 171, GETDATE(), 1);

-- South America (12 countries)
INSERT INTO Countries (Id, Name, CountryCode2, CountryCode, IsActive, SortOrder, CreatedAt, IsUNRecognized) VALUES
(NEWID(), 'Argentina', 'AR', 'ARG', 1, 172, GETDATE(), 1),
(NEWID(), 'Bolivia', 'BO', 'BOL', 1, 173, GETDATE(), 1),
(NEWID(), 'Brazil', 'BR', 'BRA', 1, 174, GETDATE(), 1),
(NEWID(), 'Chile', 'CL', 'CHL', 1, 175, GETDATE(), 1),
(NEWID(), 'Colombia', 'CO', 'COL', 1, 176, GETDATE(), 1),
(NEWID(), 'Ecuador', 'EC', 'ECU', 1, 177, GETDATE(), 1),
(NEWID(), 'Guyana', 'GY', 'GUY', 1, 178, GETDATE(), 1),
(NEWID(), 'Paraguay', 'PY', 'PRY', 1, 179, GETDATE(), 1),
(NEWID(), 'Peru', 'PE', 'PER', 1, 180, GETDATE(), 1),
(NEWID(), 'Suriname', 'SR', 'SUR', 1, 181, GETDATE(), 1),
(NEWID(), 'Uruguay', 'UY', 'URY', 1, 182, GETDATE(), 1),
(NEWID(), 'Venezuela', 'VE', 'VEN', 1, 183, GETDATE(), 1);

-- Oceania (14 countries)
INSERT INTO Countries (Id, Name, CountryCode2, CountryCode, IsActive, SortOrder, CreatedAt, IsUNRecognized) VALUES
(NEWID(), 'Australia', 'AU', 'AUS', 1, 184, GETDATE(), 1),
(NEWID(), 'Fiji', 'FJ', 'FJI', 1, 185, GETDATE(), 1),
(NEWID(), 'Kiribati', 'KI', 'KIR', 1, 186, GETDATE(), 1),
(NEWID(), 'Marshall Islands', 'MH', 'MHL', 1, 187, GETDATE(), 1),
(NEWID(), 'Micronesia', 'FM', 'FSM', 1, 188, GETDATE(), 1),
(NEWID(), 'Nauru', 'NR', 'NRU', 1, 189, GETDATE(), 1),
(NEWID(), 'New Zealand', 'NZ', 'NZL', 1, 190, GETDATE(), 1),
(NEWID(), 'Palau', 'PW', 'PLW', 1, 191, GETDATE(), 1),
(NEWID(), 'Papua New Guinea', 'PG', 'PNG', 1, 192, GETDATE(), 1),
(NEWID(), 'Samoa', 'WS', 'WSM', 1, 193, GETDATE(), 1),
(NEWID(), 'Solomon Islands', 'SB', 'SLB', 1, 194, GETDATE(), 1),
(NEWID(), 'Tonga', 'TO', 'TON', 1, 195, GETDATE(), 1),
(NEWID(), 'Tuvalu', 'TV', 'TUV', 1, 196, GETDATE(), 1),
(NEWID(), 'Vanuatu', 'VU', 'VUT', 1, 197, GETDATE(), 1);

COMMIT TRANSACTION;

-- Verify the count
SELECT COUNT(*) as 'Total Countries Inserted' FROM Countries;